// Design token data for the Token Tables documentation page.
//
// Everything here is derived from src/styles/_variables.scss at build time —
// values, types, CSS custom property names and utility classes are never
// transcribed by hand. See the Annotation Reference block at the top of
// _variables.scss for the comment conventions this file reads.
//
// Four inputs are joined by token name:
//   A. Sass module introspection  -> name, resolved value, type, source order
//   B. Bootstrap's $utilities map -> utility class names
//   C. Compiled main.css          -> emitted custom properties and their scope
//   D. Raw text of _variables.scss-> sections, guidance prose, notes
//
// Do not memoize at module scope. Eleventy re-invokes this function on every
// watch rebuild, and a cache here would serve stale tokens forever.

const fs = require("fs");
const path = require("path");
const { pathToFileURL } = require("url");
const sass = require("sass");

const STYLES_DIR = path.join(__dirname, "..", "styles");
const VARIABLES_FILE = path.join(STYLES_DIR, "_variables.scss");
// Relative to VIRTUAL_URL below. Sass cannot resolve an absolute Windows path
// in an @import, so this mirrors the form used in main.scss.
const BOOTSTRAP = "../../node_modules/bootstrap/scss";

// Bootstrap's own stack still uses @import and legacy colour functions; those
// deprecations are not ours to fix and would drown the token coverage report.
const SILENCED = ["import", "global-builtin", "color-functions"];

// Compiling a string rather than a temp file avoids Sass's loadPaths, which is
// unreliable with Windows drive letters. Giving the string a url inside
// src/styles lets relative @use and @import resolve as if it lived there.
const VIRTUAL_URL = pathToFileURL(path.join(STYLES_DIR, "__generated.scss"));

// CSS functions that may legitimately survive into a resolved token value.
// Anything else means Sass silently degraded an unresolved function call to a
// literal, which would put a broken value in the documentation.
const CSS_FUNCTIONS = new Set([
  "rgba", "rgb", "hsl", "hsla", "var", "calc", "url",
  "clamp", "min", "max", "env", "linear-gradient",
]);

// Tokens whose Sass name differs from the custom property Bootstrap emits.
const CSS_VAR_ALIASES = {
  "font-family-sans-serif": "--bs-font-sans-serif",
  "body-secondary-bg": "--bs-secondary-bg",
  "body-secondary-color": "--bs-secondary-color",
  "body-tertiary-bg": "--bs-tertiary-bg",
  "body-tertiary-color": "--bs-tertiary-color",
  "accordion-button-bg": "--bs-accordion-btn-bg",
  "accordion-button-active-bg": "--bs-accordion-active-bg",
  "accordion-button-color": "--bs-accordion-btn-color",
  "accordion-button-active-color": "--bs-accordion-active-color",
  "accordion-button-focus-box-shadow": "--bs-accordion-btn-focus-box-shadow",
  "breadcrumb-active-color": "--bs-breadcrumb-item-active-color",
};

// Bootstrap component variants generated by looping over $theme-colors rather
// than by the utilities API, so they never appear in the $utilities map.
const THEME_COLOR_COMPONENTS = ["btn", "alert", "table", "text-bg", "list-group-item"];

// Display order for the tabs, which cannot follow source order: the semantic
// tokens alias the brand tokens, so brand has to be declared first in Sass
// even though it is the tab you reach for least. Any tab not listed here
// falls to the end, in source order.
const TAB_ORDER = [
  "Semantic Colors",
  "Other Tokens",
  "Component Classes",
  "Brand Colors",
];

const COLOR_PROPERTIES = /color|background|border-color|fill|stroke/;

// Bootstrap names a utility after the role, dropping the property suffix that
// the Sass variable carries: $body-tertiary-bg is keyed "body-tertiary" and
// $body-secondary-color is keyed "body-secondary". Both keys are the same, so
// the suffix is also what tells the two apart — strip it to find the key, then
// use it to pick the right property. Longest suffix first.
const NAME_SUFFIXES = [
  { suffix: "-border-color", property: /^border-color$/ },
  { suffix: "-bg", property: /^background-color$/ },
  { suffix: "-color", property: /^color$/ },
];

// ---------------------------------------------------------------------------
// A. Token values, types and source order, straight from the Sass compiler.
// ---------------------------------------------------------------------------
function readTokens() {
  const tokens = [];
  sass.compileString(
    `@use "sass:meta";
     @use "variables" as t;
     @each $n, $v in meta.module-variables("t") {
       $_: emit-token($n, meta.inspect($v), meta.type-of($v));
     }`,
    {
      url: VIRTUAL_URL,
      functions: {
        "emit-token($name, $value, $type)": (args) => {
          tokens.push({
            name: args[0].assertString().text,
            value: args[1].assertString().text,
            type: args[2].assertString().text,
          });
          return sass.sassNull;
        },
      },
    }
  );
  return tokens;
}

// ---------------------------------------------------------------------------
// B. Utility class names, keyed by the $utilities values-map key they came
//    from. Joined to tokens by name — matching on resolved value does not work
//    because every Bootstrap colour utility resolves to var() indirection.
// ---------------------------------------------------------------------------
// meta.inspect() preserves the quotes around a quoted Sass string, so map keys
// arrive here as `"primary"` rather than `primary`.
function unquote(text) {
  return text.replace(/^["']|["']$/g, "");
}

function readUtilities() {
  const byKey = new Map();
  const add = (key, className, property, isColor) => {
    if (!byKey.has(key)) byKey.set(key, []);
    const list = byKey.get(key);
    if (!list.some((u) => u.className === className)) {
      list.push({ className, property, isColor });
    }
  };

  sass.compileString(
    `@import "${BOOTSTRAP}/functions";
     @import "variables";
     @import "${BOOTSTRAP}/variables";
     @import "${BOOTSTRAP}/variables-dark";
     @import "${BOOTSTRAP}/maps";
     @import "${BOOTSTRAP}/mixins";
     @import "${BOOTSTRAP}/utilities";

     @each $key, $util in $utilities {
       @if type-of($util) == map and map-get($util, "values") != null {
         $class: $key;
         @if map-has-key($util, "class") {
           $class: map-get($util, "class");
         }
         $property: map-get($util, "property");
         $values: map-get($util, "values");
         @if $class != null {
           @if type-of($values) == map {
             @each $vkey, $vval in $values {
               $_: emit-utility(inspect($class), inspect($vkey), inspect($property));
             }
           } @else {
             @each $vkey in $values {
               $_: emit-utility(inspect($class), inspect($vkey), inspect($property));
             }
           }
         }
       }
     }

     @each $key, $value in $theme-colors {
       $_: emit-theme-color(inspect($key));
     }`,
    {
      url: VIRTUAL_URL,
      silenceDeprecations: SILENCED,
      functions: {
        "emit-utility($class, $key, $property)": (args) => {
          const cls = unquote(args[0].assertString().text);
          const key = unquote(args[1].assertString().text);
          const property = unquote(args[2].assertString().text);
          if (key === "null" || key === "") return sass.sassNull;
          // .focus-ring-* has a null property because it sets a local custom
          // property rather than a CSS property, but it is a colour utility.
          const isColor = COLOR_PROPERTIES.test(property) || cls === "focus-ring";
          add(key, `.${cls}-${key}`, property, isColor);
          return sass.sassNull;
        },
        "emit-theme-color($key)": (args) => {
          const key = unquote(args[0].assertString().text);
          for (const component of THEME_COLOR_COMPONENTS) {
            add(key, `.${component}-${key}`, "color", true);
          }
          return sass.sassNull;
        },
      },
    }
  );
  return byKey;
}

// ---------------------------------------------------------------------------
// C. Custom properties actually emitted by the compiled stylesheet, with the
//    selector they are scoped to. This is the only authoritative source for
//    the CSS variable column — several Bootstrap tokens are renamed on the way
//    out, and most are scoped to a component rather than :root.
// ---------------------------------------------------------------------------
function readCompiledMain(brandNames) {
  const cascade = new Map();

  // Importing main.scss rather than compiling it directly lets us read the
  // brand tokens as the real cascade sees them, after every override in the
  // entry point has been applied. That is the value the module copy behind
  // --ucl-* has to agree with.
  const result = sass.compileString(
    `@import "main";
     ${brandNames
       .map((n) => `$_: emit-cascade("${n}", inspect($${n}));`)
       .join("\n     ")}`,
    {
      url: VIRTUAL_URL,
      silenceDeprecations: SILENCED,
      functions: {
        "emit-cascade($name, $value)": (args) => {
          cascade.set(
            unquote(args[0].assertString().text),
            unquote(args[1].assertString().text)
          );
          return sass.sassNull;
        },
      },
    }
  );

  const css = result.css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/@charset[^;]*;/g, "");

  const properties = new Map();
  const blockPattern = /([^{}]+)\{([^{}]*)\}/g;
  let block;
  while ((block = blockPattern.exec(css)) !== null) {
    // Selector lists wrap across lines in expanded output, so flatten first,
    // then take the first selector — Bootstrap pairs `:root` with
    // `[data-bs-theme=light]` and `:root` is the one worth documenting.
    const selector = block[1].replace(/\s+/g, " ").trim().split(",")[0].trim();
    const declarationPattern = /(--[\w-]+)\s*:\s*([^;]+)/g;
    let declaration;
    while ((declaration = declarationPattern.exec(block[2])) !== null) {
      const name = declaration[1];
      // Keep the first (outermost) definition; later ones are dark-mode or
      // component-scoped overrides of the same property.
      if (!properties.has(name)) {
        properties.set(name, { scope: selector, value: declaration[2].trim() });
      }
    }
  }
  return { properties, cascade };
}

// ---------------------------------------------------------------------------
// D. Sections, guidance prose and notes from the raw source text.
// ---------------------------------------------------------------------------

// Finds the `//` that begins a trailing comment, ignoring any that sit inside
// quotes or parentheses — `url(https://...)` and `"a // b"` are not comments.
function trailingCommentIndex(line) {
  let inSingle = false;
  let inDouble = false;
  let depth = 0;
  for (let i = 0; i < line.length - 1; i += 1) {
    const char = line[i];
    if (char === "\\") {
      i += 1;
    } else if (inSingle) {
      if (char === "'") inSingle = false;
    } else if (inDouble) {
      if (char === '"') inDouble = false;
    } else if (char === "'") {
      inSingle = true;
    } else if (char === '"') {
      inDouble = true;
    } else if (char === "(") {
      depth += 1;
    } else if (char === ")") {
      depth -= 1;
    } else if (char === "/" && line[i + 1] === "/" && depth === 0) {
      return i;
    }
  }
  return -1;
}

function readAnnotations() {
  const source = fs.readFileSync(VARIABLES_FILE, "utf8").split(/\r?\n/);
  const sections = [];
  const annotations = new Map();

  let currentTab = null;
  let current = null;
  let pendingNote = [];

  for (const line of source) {
    const trimmed = line.trim();

    // Tab marker must be tested before the section marker, since === also
    // satisfies the == pattern.
    const tabMatch = trimmed.match(/^\/\/\s*===\s*(.+?)\s*===\s*$/);
    if (tabMatch) {
      currentTab = tabMatch[1];
      current = null;
      pendingNote = [];
      continue;
    }

    const sectionMatch = trimmed.match(/^\/\/\s*==\s*(.+?)\s*==\s*$/);
    if (sectionMatch) {
      current = { label: sectionMatch[1], tab: currentTab, guidance: [] };
      sections.push(current);
      pendingNote = [];
      continue;
    }

    const guidanceMatch = trimmed.match(/^\/\/!\s?(.*)$/);
    if (guidanceMatch && current) {
      current.guidance.push(guidanceMatch[1]);
      continue;
    }

    const noteMatch = trimmed.match(/^\/\/\/\s?(.*)$/);
    if (noteMatch) {
      pendingNote.push(noteMatch[1]);
      continue;
    }

    const declarationMatch = trimmed.match(/^\$([\w-]+)\s*:/);
    if (declarationMatch) {
      const commentAt = trailingCommentIndex(line);
      const inline = commentAt === -1 ? "" : line.slice(commentAt + 2).trim();
      annotations.set(declarationMatch[1], {
        section: current ? current.label : null,
        tab: current ? current.tab : null,
        note: pendingNote.length ? pendingNote.join(" ") : inline,
      });
      pendingNote = [];
      continue;
    }

    // A blank line or any other statement ends an unattached /// block.
    if (trimmed === "") pendingNote = [];
  }

  return {
    sections: sections.map((s) => ({
      label: s.label,
      tab: s.tab,
      guidance: s.guidance.join(" ").trim(),
    })),
    annotations,
  };
}

// ---------------------------------------------------------------------------
// E. Component classes. Top-level class selectors carrying a /// note, read
//    from the partials main.scss imports — which is what excludes the
//    documentation-only components in meta.scss and the LibApps overrides,
//    without needing a list of exceptions here.
// ---------------------------------------------------------------------------
function localImportsOfMain() {
  const source = fs.readFileSync(path.join(STYLES_DIR, "main.scss"), "utf8");
  const files = [];
  const pattern = /@import\s+["']([^"']+)["']/g;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    const target = match[1];
    if (target.includes("node_modules") || target === "variables") continue;
    const dir = path.dirname(target);
    const name = path.basename(target);
    files.push(path.join(STYLES_DIR, dir, `_${name}.scss`));
  }
  return files.filter((file) => fs.existsSync(file));
}

function readComponentClasses() {
  const groups = [];

  for (const file of localImportsOfMain()) {
    const relative = path
      .relative(path.join(STYLES_DIR, ".."), file)
      .replace(/\\/g, "/");
    const lines = fs.readFileSync(file, "utf8").split(/\r?\n/);
    const classes = [];
    let pendingNote = [];

    for (const line of lines) {
      const trimmed = line.trim();

      const noteMatch = trimmed.match(/^\/\/\/\s?(.*)$/);
      if (noteMatch) {
        pendingNote.push(noteMatch[1]);
        continue;
      }

      // A selector opening a block. Only annotated ones are documented, so a
      // BEM child, a nested descendant or a pseudo-class never appears unless
      // someone deliberately wrote a note for it.
      const selectorMatch = trimmed.match(/^([.#][^{};]*?)\s*\{$/);
      if (selectorMatch && pendingNote.length) {
        classes.push({
          selector: selectorMatch[1].trim(),
          note: pendingNote.join(" "),
          file: relative,
        });
        pendingNote = [];
        continue;
      }

      if (trimmed === "" || trimmed.endsWith("{") || trimmed.endsWith(";")) {
        pendingNote = [];
      }
    }

    if (classes.length) {
      groups.push({ label: relative, guidance: "", classes });
    }
  }

  return groups;
}

// ---------------------------------------------------------------------------
// Guards
// ---------------------------------------------------------------------------

// Catches the silent failure mode where a Sass function was not in scope and
// degraded into a literal CSS function call.
function assertResolved(tokens) {
  const broken = tokens.filter((token) => {
    const match = /^([a-z][\w-]*)\(/i.exec(token.value.trim());
    return match && !CSS_FUNCTIONS.has(match[1].toLowerCase());
  });
  if (broken.length) {
    throw new Error(
      "Unresolved Sass function in _variables.scss. The value below was not " +
        "evaluated and degraded to a literal, which usually means the function " +
        "is not in scope at the point _variables.scss is imported:\n" +
        broken.map((t) => `  $${t.name}: ${t.value}`).join("\n")
    );
  }
}

// Catches divergence between the @use'd module copy of _variables.scss, which
// is what gets published as --ucl-*, and the @import'ed copy, which is what the
// rest of the stylesheet compiles against. They are separate evaluations, so
// !default or a downstream reassignment can pull them apart with no warning.
// See the Auto-Exposure Constraint note in _variables.scss.
//
// Comparing the module against the emitted custom properties would prove
// nothing, since both come from the module. The @import cascade is the other
// side of the comparison.
function assertExposureAgrees(tokens, cascade, properties) {
  const mismatches = [];
  for (const token of tokens) {
    if (!token.name.startsWith("ucl-")) continue;

    const cascadeValue = cascade.get(token.name);
    if (cascadeValue !== undefined && !sameValue(cascadeValue, token.value)) {
      mismatches.push(
        `  $${token.name} is ${token.value} as a module but ${cascadeValue} ` +
          `through @import, so --${token.name} would publish ${token.value} ` +
          `while the stylesheet compiles against ${cascadeValue}`
      );
    } else if (token.type === "color" && !properties.has(`--${token.name}`)) {
      mismatches.push(`  $${token.name} is not published as --${token.name}`);
    }
  }
  if (mismatches.length) {
    throw new Error(
      "Brand token exposure disagrees with the compiled Sass. A $ucl-* token " +
        "was probably given !default or reassigned downstream:\n" +
        mismatches.join("\n")
    );
  }
}

function sameValue(a, b) {
  return a.trim().toLowerCase() === b.trim().toLowerCase();
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

function resolveCssVar(name, properties) {
  const candidates = [
    CSS_VAR_ALIASES[name],
    `--bs-${name}`,
    `--ucl-${name}`,
    `--${name}`,
  ].filter(Boolean);
  for (const candidate of candidates) {
    if (properties.has(candidate)) {
      return { name: candidate, scope: properties.get(candidate).scope };
    }
  }
  return null;
}

function resolveUtilities(token, utilities) {
  const wantsColor = token.type === "color";
  const found = new Set();

  const take = (key, property) => {
    for (const utility of utilities.get(key) || []) {
      if (utility.isColor !== wantsColor) continue;
      if (property && !property.test(utility.property)) continue;
      found.add(utility.className);
    }
  };

  // An exact name match covers the theme colours, which Bootstrap keys on the
  // bare role: $primary -> .text-primary, .bg-primary, .btn-primary, ...
  take(token.name, null);

  // Otherwise the utility key drops the property suffix, and the suffix
  // decides which property to accept: $body-secondary-bg is .bg-body-secondary
  // while $body-secondary-color is .text-body-secondary.
  for (const rule of NAME_SUFFIXES) {
    if (token.name.endsWith(rule.suffix)) {
      take(token.name.slice(0, -rule.suffix.length), rule.property);
      break;
    }
  }

  return [...found].sort();
}

module.exports = function () {
  const rawTokens = readTokens();
  assertResolved(rawTokens);

  const brandNames = rawTokens
    .filter((token) => token.name.startsWith("ucl-"))
    .map((token) => token.name);
  const utilities = readUtilities();
  const { properties, cascade } = readCompiledMain(brandNames);
  assertExposureAgrees(rawTokens, cascade, properties);

  const { sections, annotations } = readAnnotations();

  const tokens = rawTokens
    .filter((token) => token.type !== "bool" && !token.name.startsWith("enable-"))
    .map((token) => {
      const annotation =
        annotations.get(token.name) || { section: null, tab: null, note: "" };
      const cssVar = resolveCssVar(token.name, properties);
      return {
        name: token.name,
        scss: `$${token.name}`,
        cssVar: cssVar ? cssVar.name : "",
        cssVarScope: cssVar && cssVar.scope !== ":root" ? cssVar.scope : "",
        value: token.value,
        type: token.type,
        // The swatch is a per-row decision, so a table can hold colour and
        // non-colour tokens side by side and a component's tokens stay
        // together rather than being split across tabs by type.
        swatch: token.type === "color" ? token.value : "",
        utilities: resolveUtilities(token, utilities),
        note: annotation.note,
        section: annotation.section,
        tab: annotation.tab,
      };
    });

  // Tabs are declared in _variables.scss, in source order.
  const tabs = [];
  for (const section of sections) {
    if (!section.tab) continue;
    const rows = tokens.filter((token) => token.section === section.label);
    if (!rows.length) continue;
    let tab = tabs.find((candidate) => candidate.label === section.tab);
    if (!tab) {
      tab = { id: slug(section.tab), label: section.tab, kind: "tokens", sections: [] };
      tabs.push(tab);
    }
    tab.sections.push({ ...section, tokens: rows });
  }

  const classGroups = readComponentClasses();
  if (classGroups.length) {
    tabs.push({
      id: "component-classes",
      label: "Component Classes",
      kind: "classes",
      sections: classGroups,
    });
  }

  for (const tab of tabs) {
    tab.count = tab.sections.reduce(
      (total, section) => total + (section.tokens || section.classes).length,
      0
    );
  }

  const rank = (tab) => {
    const index = TAB_ORDER.indexOf(tab.label);
    return index === -1 ? TAB_ORDER.length : index;
  };
  tabs.sort((a, b) => rank(a) - rank(b));

  const allClasses = classGroups.flatMap((group) => group.classes);
  report(tokens, allClasses);

  return { tables: tabs, all: tokens, classes: allClasses };
};

function slug(label) {
  return label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function report(tokens, classes) {
  const undocumented = tokens.filter((t) => !t.note);
  const unexposed = tokens.filter((t) => !t.cssVar);
  const untabbed = tokens.filter((t) => !t.tab);
  const byTab = new Map();
  for (const token of tokens) {
    const key = token.tab || "(no tab)";
    byTab.set(key, (byTab.get(key) || 0) + 1);
  }
  const lines = [
    `[tokens] ${tokens.length} tokens, ${classes.length} classes ` +
      `(${[...byTab].map(([tab, n]) => `${tab}: ${n}`).join(", ")})`,
  ];
  if (untabbed.length) {
    lines.push(
      `[tokens] ${untabbed.length} not in any tab, so not documented — add a ` +
        `// === Tab === marker above their section: ` +
        untabbed.map((t) => t.scss).join(", ")
    );
  }
  if (undocumented.length) {
    lines.push(
      `[tokens] ${undocumented.length} without a note: ` +
        undocumented.map((t) => t.scss).join(", ")
    );
  }
  if (unexposed.length) {
    lines.push(
      `[tokens] ${unexposed.length} without a CSS variable: ` +
        unexposed.map((t) => t.scss).join(", ")
    );
  }
  process.stderr.write(lines.join("\n") + "\n");
}
